version: "3"
virtualmachines:
- name: serv
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  machine_type: n1-standard-1
- name: work
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server
  machine_type: n1-standard-1
- name: work2
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server
  machine_type: n1-standard-1
